import json
import os
import shutil
import subprocess

context = json.loads(
    """
{{ cookiecutter | jsonify }}
"""
)

use_github_action = context["use_github_action"] == "y"

if not use_github_action:
    shutil.rmtree(".github")

# create a git repo, everybody needs this, right?
subprocess.call(["git", "init"])
subprocess.call(["git", "add", ".gitignore", ".flake8"])
subprocess.call(["git", "add", "*"])
subprocess.call(["git", "commit", "-m", "generated by cookiecutter"])

# print some help messages
home = os.path.expanduser("~")
relpath = os.path.relpath(os.getcwd(), home)
print(
    f"""
# To start working on the project,

cd ~/{relpath}
poetry install
poetry run pre-commit install
poetry run isort **/*.py
poetry run black .
poetry shell


#    Hack away!

"""
)
